.TH JAVAPRE 1
.SH NAME
javaPre \- preprocess java source files in a C-style way
.SH SYNOPSIS
.B javaPre
.IR file
.SH DESCRIPTION
.B javaPre
takes a java input file, and performs basic preprocessing tasks on Java files. See javapre(5)
.SH SEE ALSO
javac(1), javaPre(5)
.SH BUGS
Only #DEFINE is working right now.
.SH AUTHOR
Jim Read (jimmydean886@hotmail.com)
